=== alvaroisp/mti-saw/apt01/parlamentario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- definición de elementos simples -->
	<xs:element name="nombre" type="xs:string"/>
	<xs:element name="nombres" type="xs:string"/>
	<xs:element name="apellido_paterno" type="xs:string"/>
	<xs:element name="apellido_materno" type="xs:string"/>
	<xs:element name="genero" type="xs:string"/>
	<xs:element name="ciudad" type="xs:string"/>
	<xs:element name="pais" type="xs:string"/>
	<xs:element name="fecha" type="xs:date"/>
	<xs:element name="partido_politico" type="xs:string"/>
	<xs:element name="titulo" type="xs:string"/>
	<xs:element name="institucion" type="xs:string"/>
	<xs:element name="relacion" type="xs:string"/>
	<xs:element name="nombre_relacion" type="xs:string"/>
	<xs:element name="activa" type="xs:boolean"/>
	<xs:element name="fecha_inicio" type="xs:date"/>
	<xs:element name="fecha_fin" type="xs:date"/>
	<xs:element name="fecha_titulacion" type="xs:date"/>
	<xs:element name="periodo" type="xs:string"/>
	<xs:element name="representacion" type="xs:string"/>
	<xs:element name="tipo_comision" type="tipoComision"/>
	<xs:element name="rol" type="xs:string"/>
	<xs:element name="imagen" type="xs:anyURI"/>
	<xs:element name="ano_titulacion" type="xs:gYear"/>
	<xs:element name="uri" type="xs:anyURI"/>
	<!-- definición de atributos -->
	<xs:attribute name="idPersona" type="xs:positiveInteger"/>
	<!-- definición de elementos simples usados para restringir valores -->
	<xs:simpleType name="tipoComision">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Especial"/>
			<xs:enumeration value="Investigadora"/>
			<xs:enumeration value="Mixta"/>
			<xs:enumeration value="Permanente"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- definición de elementos complejos -->
	<xs:element name="nacimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ciudad"/>
				<xs:element ref="pais"/>
				<xs:element ref="fecha"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="muerte">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ciudad"/>
				<xs:element ref="pais"/>
				<xs:element ref="fecha"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="carrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="titulo"/>
				<xs:element ref="institucion"/>
				<xs:element ref="fecha_titulacion" minOccurs="0"/>
				<xs:element ref="ano_titulacion" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="grado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="institucion"/>
				<xs:element ref="fecha_titulacion" minOccurs="0"/>
				<xs:element ref="ano_titulacion" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pariente">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="relacion"/>
				<xs:element ref="nombre"/>
				<xs:element ref="nombre_relacion"/>
				<xs:element ref="activa" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cargo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="institucion"/>
				<xs:element ref="fecha_inicio"/>
				<xs:element ref="fecha_fin" minOccurs="0"/>
				<xs:element ref="periodo"/>
				<xs:element ref="representacion"/>
				<xs:element ref="partido_politico"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="comision">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="tipo_comision"/>
				<xs:element ref="institucion"/>
				<xs:element ref="rol"/>
				<xs:element ref="periodo"/>
				<xs:element ref="fecha_inicio"/>
				<xs:element ref="fecha_fin"/>
				<xs:element ref="uri" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- definición de elementos complejos basados en elementos complejos anteriores -->
	<xs:element name="identificacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="nombres"/>
				<xs:element ref="apellido_paterno"/>
				<xs:element ref="apellido_materno" minOccurs="0"/>
				<xs:element ref="genero" minOccurs="0"/>
				<xs:element ref="nacimiento"/>
				<xs:element ref="muerte" minOccurs="0"/>
				<xs:element ref="partido_politico" minOccurs="0"/>
				<xs:element ref="imagen" minOccurs="0"/>
				<xs:element ref="uri" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pregrado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="carrera" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="postgrado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="grado" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="estudios">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pregrado" minOccurs="0"/>
				<xs:element ref="postgrado" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="familia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pariente" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cargos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cargo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="comisiones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="comision" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="persona">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="identificacion"/>
				<xs:element ref="estudios" minOccurs="0"/>
				<xs:element ref="familia" minOccurs="0"/>
				<xs:element ref="cargos"/>
				<xs:element ref="comisiones" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute ref="idPersona" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alvaroisp/mti-saw/apt01/enrique_accorsi.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="parlamentario.xslt"?>
<persona idPersona="2200" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parlamentario.xsd">
	<identificacion>
		<nombre>Enrique Luis Accorsi Opazo</nombre>
		<nombres>Enrique Luis</nombres>
		<apellido_paterno>Accorsi</apellido_paterno>
		<apellido_materno>Opazo</apellido_materno>
		<genero>masculino</genero>
		<nacimiento>
			<ciudad>Santiago</ciudad>
			<pais>Chile</pais>
			<fecha>1948-08-17</fecha>
		</nacimiento>
		<partido_politico>Partido Por la Democracia</partido_politico>
		<imagen>http://biografias.bcn.cl/images/a/a4/Enrique_Accorsi_Opazo.jpg</imagen>
		<uri>http://datos.bcn.cl/recurso/persona/2200</uri>
	</identificacion>
	<estudios><pregrado>
		<carrera>
			<titulo>Médico Cirujano</titulo>
			<institucion>Universidad Católica de Chile</institucion>
		</carrera>
	</pregrado><postgrado>
		<grado>
			<nombre>Especialización Cirugía Pediátrica</nombre>
			<institucion>Universidad de Chile</institucion>
		</grado>
		<grado>
			<nombre>Especialización Cirugía Ortopédica</nombre>
			<institucion>Universidad de Chile</institucion>
		</grado>
		<grado>
			<nombre>Cirugía Neonatal</nombre>
			<institucion>Hospital Valle Hebrón de Barcelona, España</institucion>
			<ano_titulacion>1981</ano_titulacion>
		</grado>
	</postgrado></estudios>
	<cargos>
		<cargo>
			<nombre>Diputado</nombre>
			<institucion>Cámara</institucion>
			<fecha_inicio>2010-03-11</fecha_inicio>
			<fecha_fin>2014-03-10</fecha_fin>
			<periodo>2010-2014</periodo>
			<representacion>Distrito Nº 24 de Región Metropolitana</representacion>
			<partido_politico>Partido Por la Democracia</partido_politico>
		</cargo>
		<cargo>
			<nombre>Diputado</nombre>
			<institucion>Cámara</institucion>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
			<periodo>2006-2010</periodo>
			<representacion>Distrito Nº 24 de Región Metropolitana</representacion>
			<partido_politico>Partido Por la Democracia</partido_politico>
		</cargo>
		<cargo>
			<nombre>Diputado</nombre>
			<institucion>Cámara</institucion>
			<fecha_inicio>2002-03-11</fecha_inicio>
			<fecha_fin>2006-03-10</fecha_fin>
			<periodo>2002-2006</periodo>
			<representacion>Distrito Nº 24 de Región Metropolitana</representacion>
			<partido_politico>Partido Por la Democracia</partido_politico>
		</cargo>
	</cargos>
	<comisiones>
		<comision>
			<nombre>Salud</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2010-2014</periodo>
			<fecha_inicio>2010-03-11</fecha_inicio>
			<fecha_fin>2014-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=411]]></uri>
		</comision>
		<comision>
			<nombre>Recursos Naturales y Superación de Pobreza, Planificación y Desarrollo Social</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2010-2014</periodo>
			<fecha_inicio>2010-03-11</fecha_inicio>
			<fecha_fin>2014-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=405]]></uri>
		</comision>
		<comision>
			<nombre>Deportes</nombre>
			<tipo_comision>Especial</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2010-2014</periodo>
			<fecha_inicio>2010-03-11</fecha_inicio>
			<fecha_fin>2014-03-10</fecha_fin>
		</comision>
		<comision>
			<nombre>Recursos Naturales, Bienes Nacionales y Medio Ambiente</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=405]]></uri>
		</comision>
		<comision>
			<nombre>Derechos Humanos, Nacionalidad y Ciudadanía</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=404]]></uri>
		</comision>
		<comision>
			<nombre>Superación de la Pobreza, Planificación y Desarrollo Social</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=553]]></uri>
		</comision>
		<comision>
			<nombre>Relaciones Exteriores, Asuntos Interparlamentarios e Integración Latinoamericana</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=406]]></uri>
		</comision>
		<comision>
			<nombre>Conducta Parlamentaria</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=544]]></uri>
		</comision>
		<comision>
			<nombre>Discapacitados</nombre>
			<tipo_comision>Especial</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
		</comision>
		<comision>
			<nombre>Deportes</nombre>
			<tipo_comision>Especial</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=789]]></uri>
		</comision>
		<comision>
			<nombre>Estudio del Régimen Político Chileno</nombre>
			<tipo_comision>Especial</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
		</comision>
		<comision>
			<nombre>Contaminación por Plomo en Arica</nombre>
			<tipo_comision>Investigadora</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2006-2010</periodo>
			<fecha_inicio>2006-03-11</fecha_inicio>
			<fecha_fin>2010-03-10</fecha_fin>
		</comision>
		<comision>
			<nombre>Salud</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2002-2006</periodo>
			<fecha_inicio>2002-03-11</fecha_inicio>
			<fecha_fin>2006-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=411]]></uri>
		</comision>
		<comision>
			<nombre>Derechos Humanos, Nacionalidad y Ciudadanía</nombre>
			<tipo_comision>Permanente</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2002-2006</periodo>
			<fecha_inicio>2002-03-11</fecha_inicio>
			<fecha_fin>2006-03-10</fecha_fin>
			<uri><![CDATA[https://www.camara.cl/trabajamos/comision_portada.aspx?prmID=404]]></uri>
		</comision>
		<comision>
			<nombre>Establece Beneficios para los Discapacitados</nombre>
			<tipo_comision>Especial</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2002-2006</periodo>
			<fecha_inicio>2002-03-11</fecha_inicio>
			<fecha_fin>2006-03-10</fecha_fin>
		</comision>
		<comision>
			<nombre>Contaminación por Plomo en Arica</nombre>
			<tipo_comision>Investigadora</tipo_comision>
			<institucion>Cámara</institucion>
			<rol>miembro</rol>
			<periodo>2002-2006</periodo>
			<fecha_inicio>2002-03-11</fecha_inicio>
			<fecha_fin>2006-03-10</fecha_fin>
		</comision>
	</comisiones>
</persona>
